name: Selenium IDE CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/checkout@v3
        with:
         dotnet-version: '6.0.x'
      - name: Install Chrome
        run: |
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
      - name: Set executable permissions for Selenium Manager
        run: chmod +x /home/runner/work/SeleniumIde-CI_Exercise-/SeleniumIde-CI_Exercise-/SeleniumIDE/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
      - name: Install dependencies
        run: dotnet restore
      - name: Build the Solution
        run: dotnet build --no-restore
      - name: Run Tests
        env: 
          CHROMEWEBDRIVER: /usr/bin/google-chrome
        run: dotnet test --verbosity normal
