name: Selenium IDE CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/checkout@v3
        with:
         dotnet-version: '6.0.x'
      - name: Install Chrome
        run: |
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
         - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //g')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
        wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
      - name: Install dependencies
        run: dotnet restore
      - name: Build the Solution
        run: dotnet build --no-restore
      - name: Run Tests
        env: 
          CHROMEWEBDRIVER: C:\Program Files\Google\Chrome\Application\chrome.exe
        run: dotnet test --verbosity normal
